---
#Install samba
- name: install samba
  apt:
    name: samba
    state: present
    update_cache: true
  become: true


- name: Package | Install os packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ os_packages }}"
