---
- name: Include OS specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags: always

- name: updating os
  include_tasks: "tasks/update.yml"
  tags: always

- name: Include req
  include_tasks: "tasks/install.yml"
  tags: always

#- name: Containers | Docker and Podman
#  include_vars: "vars/Containers.yml"
#  tags: always